apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.haproxy.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.haproxy.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.haproxy.name }}
    namespace: {{ .Values.haproxy.namespace }}
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: {{ .Values.haproxy.name }}
